Repository kargakis/acs-engine, pull requests merged in 2018-04, with the labels that each got.

#57 inline router component
  examples/openshift.json
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/openshiftmasterscript.sh
  parts/k8s/openshiftrouter.json
  parts/k8s/openshiftrouter.parameters.json
  pkg/acsengine/const.go
  pkg/acsengine/defaults.go
  pkg/acsengine/engine.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/certgen/config.go
  pkg/certgen/templates/master/etc/origin/master/master-config.yaml
  pkg/certgen/tls.go
Labels: lgtm, size/L

#65 Added support for origin in start scripts.
  parts/k8s/openshiftmasterscript.sh
  parts/k8s/openshiftnodescript.sh
Labels: lgtm, size/M

#66 Ensure openshift.json is valid json.
  examples/openshift.json
Labels: lgtm, size/XS

#72 Drop redundant image fields
  pkg/api/agentPoolOnlyApi/vlabs/types.go
  pkg/api/agentPoolOnlyApi/vlabs/validate.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
Labels: lgtm, size/S

#74 Set username and password dynamically in .htpasswd
  examples/openshift.json
  parts/k8s/openshiftmasterscript.sh
  pkg/acsengine/defaults.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/certgen/config.go
  pkg/certgen/files.go
  pkg/certgen/templates/master/etc/origin/master/htpasswd
Labels: lgtm, size/M

#69 enable azure cloud provider
  examples/openshift.json
  parts/k8s/openshiftmasterscript.sh
  pkg/acsengine/defaults.go
  pkg/acsengine/engine.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/certgen/config.go
  pkg/certgen/files.go
  pkg/certgen/templates/master/etc/origin/master/master-config.yaml
  pkg/certgen/templates/master/tmp/bootstrapconfigs/compute-config.yaml
  pkg/certgen/templates/master/tmp/bootstrapconfigs/infra-config.yaml
  pkg/certgen/templates/master/tmp/bootstrapconfigs/master-config.yaml
  pkg/certgen/templates/node/etc/azure/azure.conf
  pkg/filesystem/filesystem.go
Labels: lgtm, size/L

#77 Prepare us for the first PR
  cmd/deploy.go
  examples/classic/kubernetes.classic.json
  examples/openshift.json
  glide.yaml
  pkg/api/common/const.go
  pkg/api/convertertoapi.go
  pkg/api/orchestrators.go
  pkg/api/orchestrators_test.go
Labels: lgtm, size/M

#79 Revert master customdata changes
  parts/k8s/kubernetesmastercustomdata.yml
Labels: lgtm, size/S

#80 More tidy ups
  parts/agentparams.t
  parts/k8s/kubernetesagentvars.t
  pkg/acsengine/engine.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
Labels: lgtm, size/M

#82 Moar
  cmd/scale.go
  examples/openshift.json
  parts/k8s/kubernetesmasterresources.t
  pkg/acsengine/engine.go
Labels: lgtm, size/S

#81 remove necessity to specify dummy certificateProfile
  examples/openshift.json
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
Labels: lgtm, size/M

#73 re-use openshift-ansible playbooks for router deploy
  parts/k8s/openshiftmasterscript.sh
  pkg/certgen/templates/master/tmp/ansible-playbooks/azure-local-master-inventory.yml
  pkg/certgen/templates/master/tmp/ansible-playbooks/deploy-router.yml
  pkg/certgen/tls.go
Labels: lgtm, size/M

#84 exclude dockerEngineDownloadRepo and dockerEngineVersion when running OpenShift
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  pkg/acsengine/engine.go
Labels: lgtm, size/S

#83 validate AvailabilityProfile for OpenShift
  pkg/api/vlabs/validate.go
Labels: lgtm, size/XS

#91 Move certgen/filesystem utilities in an openshift package
  .gitignore
  pkg/acsengine/defaults.go
  pkg/openshift/certgen/config.go
  pkg/openshift/certgen/doc.go
  pkg/openshift/certgen/files.go
  pkg/openshift/certgen/kubeconfig.go
  pkg/openshift/certgen/templates/master/etc/etcd/etcd.conf
  pkg/openshift/certgen/templates/master/etc/origin/master/htpasswd
  pkg/openshift/certgen/templates/master/etc/origin/master/master-config.yaml
  pkg/openshift/certgen/templates/master/etc/origin/master/scheduler.json
  pkg/openshift/certgen/templates/master/etc/origin/master/session-secrets.yaml
  pkg/openshift/certgen/templates/master/tmp/ansible/ansible.sh
  pkg/openshift/certgen/templates/master/tmp/ansible/azure-local-master-inventory.yml
  pkg/openshift/certgen/templates/master/tmp/ansible/deploy-router.yml
  pkg/openshift/certgen/templates/master/tmp/ansible/service-catalog.yaml
  pkg/openshift/certgen/templates/master/tmp/bootstrapconfigs/compute-config.yaml
  pkg/openshift/certgen/templates/master/tmp/bootstrapconfigs/infra-config.yaml
  pkg/openshift/certgen/templates/master/tmp/bootstrapconfigs/master-config.yaml
  pkg/openshift/certgen/templates/node/etc/azure/azure.conf
  pkg/openshift/certgen/templates/node/etc/origin/node/node-dnsmasq.conf
  pkg/openshift/certgen/templates/node/etc/origin/node/resolv.conf
  pkg/openshift/certgen/templates/templates.go
  pkg/openshift/certgen/tls.go
  pkg/openshift/doc.go
  pkg/openshift/filesystem/filesystem.go
  scripts/validate-go.sh
Labels: lgtm, size/S

#90 Stop validating certgen/templates
  pkg/openshift/certgen/files.go
  pkg/openshift/certgen/novalidate.go
  scripts/validate-go.sh
Labels: lgtm, size/M

#92 don't hardcode minor version number
  parts/k8s/openshiftmasterscript.sh
  pkg/openshift/certgen/templates/master/tmp/ansible/ansible.sh
Labels: lgtm, size/S

#95 Create (and then discover) storage account for registry
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/openshiftmasterscript.sh
  pkg/api/types.go
Labels: lgtm, size/S

#100 Deploy local registry and router in a single playbook
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/openshiftmasterscript.sh
  parts/k8s/openshiftnodescript.sh
  pkg/openshift/certgen/templates/master/tmp/ansible/ansible.sh
  pkg/openshift/certgen/templates/master/tmp/ansible/azure-local-master-inventory.yml
  pkg/openshift/certgen/templates/master/tmp/ansible/deploy-router-registry.yml
  pkg/openshift/certgen/templates/master/tmp/ansible/deploy-router.yml
Labels: lgtm, size/M

#102 Fixups
  examples/openshift.json
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/openshiftnodescript.sh
  pkg/acsengine/engine.go
  pkg/api/agentPoolOnlyApi/vlabs/types.go
  pkg/api/const.go
  pkg/api/convertertoagentpoolonlyapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
Labels: lgtm, size/L

#105 Drop some defaulted values from openshift.json
  examples/openshift.json
Labels: lgtm, size/M

#107 autoprovision managed disks for azure PVs, otherwise it doesn't work
  parts/k8s/openshiftmasterscript.sh
Labels: size/XS

#106 deploy web console with ansible
  parts/k8s/openshiftmasterscript.sh
  pkg/openshift/certgen/templates/master/tmp/ansible/ansible.sh
  pkg/openshift/certgen/templates/master/tmp/ansible/azure-local-master-inventory.yml
  pkg/openshift/certgen/templates/master/tmp/ansible/azure-ocp-deploy.yml
Labels: lgtm, size/M
