Repository kargakis/acs-engine, pull requests merged in 2018-03, with the labels that each got.

#3 make openshift orchestrator output ARM template from azure-ansible 3.7 refarch
  cmd/deploy.go
  cmd/root.go
  examples/classic/kubernetes.classic.json
  examples/openshift.json
  parts/openshift/base.t
  parts/openshift/outputs.t
  parts/openshift/params.t
  parts/openshift/resources.t
  parts/openshift/vars.t
  pkg/acsengine/engine.go
  pkg/api/common/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/orchestrators.go
  pkg/api/orchestrators_test.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
Labels: lgtm

#4 test OpenShift orchestrator in engine test
  pkg/acsengine/testdata/simple/openshift.json
Labels: lgtm, size/M

#13 disable package_version check in openshift ansible, work around bz1551862
  parts/openshift/3.7/bastion.sh
Labels: lgtm, size/XS

#17 Plumb custom image
  parts/openshift/3.7/bastion.json
  parts/openshift/3.7/infranode.json
  parts/openshift/3.7/master.json
  parts/openshift/3.7/node.json
  parts/openshift/params.t
  parts/openshift/resources.t
  parts/openshift/vars.t
  pkg/acsengine/engine.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
Labels: lgtm, size/L

#20 use certgen to generate openshift cluster config
  examples/openshift.json
  glide.yaml
  parts/openshift/3.7/bastion.json
  parts/openshift/3.7/bastion.sh
  parts/openshift/3.7/infranode.json
  parts/openshift/3.7/master.json
  parts/openshift/3.7/master.sh
  parts/openshift/3.7/node.json
  parts/openshift/3.7/node.sh
  parts/openshift/base.t
  parts/openshift/master.sh
  parts/openshift/node.sh
  parts/openshift/openshift.json
  parts/openshift/openshift.parameters.json
  parts/openshift/outputs.t
  parts/openshift/params.t
  parts/openshift/resources.t
  parts/openshift/router.json
  parts/openshift/router.parameters.json
  parts/openshift/vars.t
  pkg/acsengine/defaults.go
  pkg/acsengine/engine.go
  pkg/acsengine/testdata/simple/openshift.json
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  vendor/github.com/jim-minter/certgen/.gitignore
  vendor/github.com/jim-minter/certgen/cmd/certgen/main.go
  vendor/github.com/jim-minter/certgen/cmd/diff/diff.go
  vendor/github.com/jim-minter/certgen/cmd/diff/main.go
  vendor/github.com/jim-minter/certgen/pkg/certgen/config.go
  vendor/github.com/jim-minter/certgen/pkg/certgen/files.go
  vendor/github.com/jim-minter/certgen/pkg/certgen/kubeconfig.go
  vendor/github.com/jim-minter/certgen/pkg/certgen/templates/bindata.go
  vendor/github.com/jim-minter/certgen/pkg/certgen/templates/master/etc/etcd/etcd.conf
  vendor/github.com/jim-minter/certgen/pkg/certgen/templates/master/etc/origin/master/htpasswd
  vendor/github.com/jim-minter/certgen/pkg/certgen/templates/master/etc/origin/master/master-config.yaml
  vendor/github.com/jim-minter/certgen/pkg/certgen/templates/master/etc/origin/master/openshift-ansible-catalog-console.js
  vendor/github.com/jim-minter/certgen/pkg/certgen/templates/master/etc/origin/master/policy.json
  vendor/github.com/jim-minter/certgen/pkg/certgen/templates/master/etc/origin/master/scheduler.json
  vendor/github.com/jim-minter/certgen/pkg/certgen/templates/master/etc/origin/master/session-secrets.yaml
  vendor/github.com/jim-minter/certgen/pkg/certgen/templates/node/etc/origin/node/node-config.yaml
  vendor/github.com/jim-minter/certgen/pkg/certgen/templates/node/etc/origin/node/node-dnsmasq.conf
  vendor/github.com/jim-minter/certgen/pkg/certgen/templates/node/etc/origin/node/resolv.conf
  vendor/github.com/jim-minter/certgen/pkg/certgen/templates/templates.go
  vendor/github.com/jim-minter/certgen/pkg/certgen/tls.go
  vendor/github.com/jim-minter/certgen/pkg/filesystem/filesystem.go
Labels: lgtm, size/XXL

#36 minor followups to certgen work
  parts/openshift/master.sh
  parts/openshift/node.sh
  parts/openshift/openshift.json
Labels: lgtm, size/S

#38 3.9 support
  examples/openshift.json
  glide.yaml
  parts/openshift/master.sh
  parts/openshift/node.sh
  parts/openshift/openshift.json
  pkg/acsengine/defaults.go
  pkg/acsengine/engine.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/certgen/config.go
  pkg/certgen/files.go
  pkg/certgen/kubeconfig.go
  pkg/certgen/templates/bindata.go
  pkg/certgen/templates/master/etc/etcd/etcd.conf
  pkg/certgen/templates/master/etc/origin/master/htpasswd
  pkg/certgen/templates/master/etc/origin/master/master-config.yaml
  pkg/certgen/templates/master/etc/origin/master/policy.json
  pkg/certgen/templates/master/etc/origin/master/scheduler.json
  pkg/certgen/templates/master/etc/origin/master/session-secrets.yaml
  pkg/certgen/templates/node/etc/origin/node/node-config.yaml
  pkg/certgen/templates/node/etc/origin/node/node-dnsmasq.conf
  pkg/certgen/templates/node/etc/origin/node/resolv.conf
  pkg/certgen/templates/templates.go
  pkg/certgen/tls.go
  pkg/filesystem/filesystem.go
  scripts/validate-go.sh
  vendor/github.com/jim-minter/certgen/.gitignore
  vendor/github.com/jim-minter/certgen/cmd/certgen/main.go
  vendor/github.com/jim-minter/certgen/cmd/diff/diff.go
  vendor/github.com/jim-minter/certgen/cmd/diff/main.go
  vendor/github.com/jim-minter/certgen/pkg/certgen/templates/bindata.go
  vendor/github.com/jim-minter/certgen/pkg/certgen/templates/master/etc/origin/master/openshift-ansible-catalog-console.js
Labels: lgtm, size/XXL

#41 remove template outputs
  parts/openshift/openshift.json
  pkg/certgen/templates/bindata.go
  pkg/certgen/templates/templates.go
Labels: lgtm, size/M

#42 use golden image
  examples/openshift.json
  parts/openshift/master.sh
  parts/openshift/node.sh
  parts/openshift/openshift.parameters.json
  pkg/acsengine/engine.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
Labels: lgtm, size/XL

#40 Bootstrap
  parts/openshift/master.sh
  parts/openshift/node.sh
  pkg/certgen/kubeconfig.go
  pkg/certgen/templates/bindata.go
  pkg/certgen/templates/master/etc/origin/master/master-config.yaml
  pkg/certgen/tls.go
Labels: lgtm, size/L

#48 don't create node certs any more
  parts/openshift/master.sh
  pkg/acsengine/defaults.go
  pkg/certgen/kubeconfig.go
  pkg/certgen/templates/bindata.go
  pkg/certgen/templates/master/tmp/bootstrapconfigs/compute-config.yaml
  pkg/certgen/templates/master/tmp/bootstrapconfigs/infra-config.yaml
  pkg/certgen/templates/master/tmp/bootstrapconfigs/master-config.yaml
  pkg/certgen/tls.go
Labels: lgtm, size/L

#47 Approve CSRs for bootstrapping the cluster
  parts/openshift/master.sh
Labels: lgtm, size/S

#45 Set of small improvements
  .gitignore
  parts/openshift/master.sh
  parts/openshift/node.sh
  parts/openshift/openshift.parameters.json
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/vlabs/validate.go
  pkg/certgen/templates/bindata.go
  pkg/certgen/templates/master/etc/origin/master/policy.json
  pkg/certgen/templates/templates.go
Labels: lgtm, size/XXL

#50 Reduce templatization
  parts/openshift/openshift.json
  pkg/acsengine/defaults.go
  pkg/acsengine/engine.go
  pkg/certgen/config.go
  pkg/certgen/files.go
  pkg/certgen/kubeconfig.go
  pkg/certgen/templates/master/etc/etcd/etcd.conf
  pkg/certgen/templates/master/etc/origin/master/master-config.yaml
  pkg/certgen/tls.go
Labels: lgtm, size/L

#52 add service catalog support
  parts/openshift/master.sh
  pkg/certgen/kubeconfig.go
  pkg/certgen/templates/master/tmp/bootstrapconfigs/master-config.yaml
  pkg/certgen/templates/master/tmp/service-catalog/objects.yaml
  pkg/certgen/tls.go
Labels: lgtm, size/L

#51 Migrate openshift template into k8s
  parts/agentoutputs.t
  parts/agentparams.t
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesagentvars.t
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  parts/k8s/openshiftmasterscript.sh
  parts/k8s/openshiftnodescript.sh
  parts/k8s/openshiftrouter.json
  parts/k8s/openshiftrouter.parameters.json
  parts/masterparams.t
  parts/openshift/openshift.json
  parts/openshift/openshift.parameters.json
  pkg/acsengine/const.go
  pkg/acsengine/defaults.go
  pkg/acsengine/engine.go
  pkg/api/agentPoolOnlyApi/vlabs/types.go
  pkg/api/agentPoolOnlyApi/vlabs/validate.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoagentpoolonlyapi.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
Labels: lgtm, size/XXL

#59 update example for new upstream template usage
  examples/openshift.json
Labels: lgtm, size/M

#61 Drop redundant templatization
  parts/k8s/kubernetesparams.t
Labels: lgtm, size/XS
